/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.uno;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author KESARA
 */
public class RegisterPlayers extends javax.swing.JFrame {
    
    public ArrayList<String> playerNames;

    /**
     * Creates new form RegisterPlayers
     */
    public RegisterPlayers() {
        initComponents();
        playerNames = new ArrayList<>();
    }
    
    public String[] getNames(){
        String[] names = playerNames.toArray(new String[playerNames.size()]);
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        playerOneLabel = new javax.swing.JLabel();
        playerTwoLabel = new javax.swing.JLabel();
        playerThreeLabel = new javax.swing.JLabel();
        playerFourLabel = new javax.swing.JLabel();
        playerNameTextBox = new javax.swing.JTextField();
        playerFiveLabel = new javax.swing.JLabel();
        playerSevenLabel = new javax.swing.JLabel();
        playerNineLabel = new javax.swing.JLabel();
        playerSixLabel = new javax.swing.JLabel();
        playerEightLabel = new javax.swing.JLabel();
        playerTenLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 436));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 436));

        jLabel1.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSERT THE NAMES OF THE PLAYERS");

        saveButton.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        doneButton.setFont(new java.awt.Font("EngraversGothic BT", 0, 18)); // NOI18N
        doneButton.setText("DONE");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NAME :");

        playerOneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerOneLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerTwoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerTwoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerThreeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerThreeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerFourLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerFourLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerNameTextBox.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        playerNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameTextBoxActionPerformed(evt);
            }
        });

        playerFiveLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        playerSevenLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerSevenLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerNineLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerNineLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerSixLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerSixLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerEightLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerEightLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        playerTenLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        playerTenLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(playerNineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerSevenLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerThreeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerOneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(playerFiveLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(playerFourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerSixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerEightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerTenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(playerNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 399, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(playerTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerFourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerSixLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(playerOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerFiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerEightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerSevenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerNineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(playerTenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(playerNameTextBox.getText().isEmpty()){
            JLabel message = new JLabel("Please enter a name");
            message.setFont(new Font("Arial",Font.BOLD,48));
            JOptionPane.showMessageDialog(null,message);
        }
        else {
            String name = playerNameTextBox.getText().trim();
            playerNames.add(name);
            
            if (playerNames.size()== 1){
                playerOneLabel.setText(playerNames.get(0));
            }
            else if (playerNames.size()==2){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
            }
            else if (playerNames.size()==3){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
            }
            else if (playerNames.size()==4){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
            }
            else if (playerNames.size()==5){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
            }
            else if (playerNames.size()==6){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
                playerSixLabel.setText(playerNames.get(5));
            }
            else if (playerNames.size()==7){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
                playerSixLabel.setText(playerNames.get(5));
                playerSevenLabel.setText(playerNames.get(6));  
            }
            else if (playerNames.size()==8){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
                playerSixLabel.setText(playerNames.get(5));
                playerSevenLabel.setText(playerNames.get(6)); 
                playerEightLabel.setText(playerNames.get(7)); 
            }
            else if (playerNames.size()==9){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
                playerSixLabel.setText(playerNames.get(5));
                playerSevenLabel.setText(playerNames.get(6)); 
                playerEightLabel.setText(playerNames.get(7)); 
                playerNineLabel.setText(playerNames.get(8)); 
            }
            else if (playerNames.size()==10){
                playerOneLabel.setText(playerNames.get(0));
                playerTwoLabel.setText(playerNames.get(1));
                playerThreeLabel.setText(playerNames.get(2));
                playerFourLabel.setText(playerNames.get(3));
                playerFiveLabel.setText(playerNames.get(4));
                playerSixLabel.setText(playerNames.get(5));
                playerSevenLabel.setText(playerNames.get(6)); 
                playerEightLabel.setText(playerNames.get(7)); 
                playerNineLabel.setText(playerNames.get(8)); 
                playerNineLabel.setText(playerNames.get(9)); 
            }
            
            
            if (playerNames.size()>0 && playerNames.size()<11){
                JLabel message = new JLabel("Successful Save!");
                message.setFont(new Font("Arial",Font.BOLD,48));
                JOptionPane.showMessageDialog(null,message);
                playerNameTextBox.setText("");
            }
            
            if (playerNames.size()==11){
                playerNames.remove(name);
                JLabel message = new JLabel("There can only be 2-4 players!");
                message.setFont(new Font("Arial",Font.BOLD,48));
                JOptionPane.showMessageDialog(null,message);
                playerNameTextBox.setText("");
            }    
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        if (playerNames.size()==1 || playerNames.size()==0){
            JLabel message = new JLabel("There must be at least 2 players!");
            message.setFont(new Font("Arial",Font.BOLD,48));
            JOptionPane.showMessageDialog(null,message);
            playerNameTextBox.setText("");
        }
        else {
            
            //new Menu().setVisible(true);
            this.dispose();
            new GameStage(playerNames).setVisible(true);
            
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    private void playerNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerNameTextBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerEightLabel;
    private javax.swing.JLabel playerFiveLabel;
    private javax.swing.JLabel playerFourLabel;
    private javax.swing.JTextField playerNameTextBox;
    private javax.swing.JLabel playerNineLabel;
    private javax.swing.JLabel playerOneLabel;
    private javax.swing.JLabel playerSevenLabel;
    private javax.swing.JLabel playerSixLabel;
    private javax.swing.JLabel playerTenLabel;
    private javax.swing.JLabel playerThreeLabel;
    private javax.swing.JLabel playerTwoLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
